Hello: Здравей
Home: Начало
Login: Вход
Logout: Изход
Blog: Блог
ProjectName: ModernSteward
Success: Успех
AddPluginTitle: Добавяне на плъгин
HomepageDescr: Добрем, тук трябва да поставим някво кратичко обяснение в 1-2 изречение ;) Колко му е? Добрем, тук трябва да поставим някво кратичко обяснение в 1-2 изречение ;) Колко му е? Добрем, тук трябва да поставим някво кратичко обяснение в 1-2 изречение ;) Колко му е?
Download: Свали ModernSteward
Source: Изходен код
Content: Съдържание
AdminPanel: Администраторски панел
Users: Потребители
ListUsers: Списък с потребители
Help: Помощ
AddEntry: Добави пост
AddPlugin: Добави плъгин

BlogSlug: Линк
BlogTitle: Заглавие
BlogDescription: Описание
BlogPost: Пост

PluginName: Име
PluginDescription: Описание
PluginFile: Файл

Dashboard: Табло
AdminWelcome: Добре дошли!
AdminHome: От тук можете да управлявате съдържанието представено на потребителите.
PostsCount: Публикации
UsersCount: Потребителя
PluginsCount: Добавки
