Hello: Hello
Home: Home
Login: Login
Logout: Logout
Blog: Blog
ProjectName: ModernSteward
Success: Success
AddPluginTitle: Adding plugin
HomepageDescr: Добрем, тук трябва да поставим някво кратичко обяснение в 1-2 изречение ;) Колко му е?
Download: Download ModernSteward
Source: Source code
Content: Content
AdminPanel: Admin
Users: Users
ListUsers: List users
Help: Help
AddEntry: Add post
AddPlugin: Add plugin

BlogSlug: Slug
BlogTitle: Title
BlogDescription: Description
BlogPost: Post

PluginName: Name
PluginDescription: Description
PluginFile: File

Dashboard: Dashboard
AdminWelcome: Welcome!
AdminHome: The content shown to users can be controlled here.
PostsCount: Posts
UsersCount: Users
PluginsCount: Plugins
