Hello: Hello
Home: Home
Login: Login
Logout: Logout
Blog: Blog
ProjectName: ModernSteward
Success: Success
AddPluginTitle: Adding plugin
HomepageDescr: Make your life easier by downloading and using the application now. And remember, if you need any additional functionality - search for such a plugin in the PluginMarket. Have fun!
Download: Download ModernSteward
Source: Source code
Content: Content
AdminPanel: Admin
Users: Users
ListUsers: List users
Help: Help
AddEntry: Add post
AddPlugin: Add plugin

BlogSlug: Slug
BlogTitle: Title
BlogDescription: Description
BlogPost: Post

PluginName: Name
PluginDescription: Description
PluginFile: File

Dashboard: Dashboard
AdminWelcome: Welcome!
AdminHome: The content shown to users can be controlled here.
PostsCount: Posts
UsersCount: Users
PluginsCount: Plugins
