Default: &defaults
  database: shit.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: shit_test.sqlite3
  <<: *defaults

Staging:
  database: shit_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: shit_production.sqlite3
  poolsize: 100
  <<: *defaults
